
function searchlight_roi_sample(test_flag,firstsub)
% clear all;
% cd /mnt/englewood/data/PSYCH-PHYS/behavioural;
% load subj_ids_key;
% test case:
addpath('/home/younglw/scripts')

if test_flag
	sub=3;
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    % 	'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    % 	{'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath'},'_fourcondsCross');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'harm' 'purity' 'phys' 'psyc' 'inc' 'path'},'_sixconds');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[25:48],3,...
    %     {'inc_puronly' 'path_puronly'},'_Bpurity');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'disgweight' 'hother_scale' 'hself_scale' 'wrongscale'},'_nine');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'disgweight'},'_fourDisg');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'harm' 'purity' 'disgweight'},'_simpledisg');

    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'path'},'_pathonly');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'inc'},'_inconly');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'phys'},'_physonly');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'psyc'},'_psyconly');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:60],3,...
    %     {'harmVpurity_60' 'phys_60' 'psyc_60' 'physVpsyc_60' 'path_60' 'inc_60' 'incVpath_60'},'_sixty');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'hself_scale'},'_hselfonly');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'sit_attr'},'_sitattronly');
    % searchlight_all_regress_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %     'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %     {'person_attr'},'_persattronly');
    % searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %   'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %   {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath'},'harm_PC','_cat2');
    % searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %   'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %   {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'hother_scale'},'harm_PC','_cont2');
    % searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %   'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %   {'hother_scale' 'hself_scale' 'sit_attr' 'person_attr' 'disgweight' 'rationality' 'weird' 'acc_wrong' 'int_wrong' 'env' 'act' 'mind'},'harm_PC','_many2');
    % searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
    %   'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
    %   {'hother_scale' 'hself_scale' 'sit_attr' 'person_attr' 'disgweight' 'rationality' 'weird' 'acc_wrong' 'int_wrong' 'env' 'act' 'mind'},'purity_LIFG','_many2');
    searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
      {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'mind_raw'},'purity_LIFG', '_rawmind');
    searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
      {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'disg_raw'},'purity_LIFG', '_rawdisg');
    searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
      {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'env_raw'},'harm_PC', '_rawenv');
    searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
      {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'person_attr_raw'},'harm_PC', '_rawPA');
    
else
    for sub=firstsub:47
        try
     searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
      {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'mind_raw'},'purity_LIFG', '_rawmind');
    searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
      {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'disg_raw'},'purity_LIFG', '_rawdisg');
    searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
      {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'env_raw'},'harm_PC', '_rawenv');
    searchlight_all_regress_roi_pleiades('/home/younglw/server/englewood/mnt/englewood/data',...
      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub,[1:48],3,...
      {'phys' 'psyc' 'inc' 'path' 'physVpsyc' 'incVpath' 'person_attr_raw'},'harm_PC', '_rawPA');
        catch
            disp(['Could not process subject ' num2str(sub)]);
            continue
        end
    end
end


end % end function