
cd /mnt/englewood/data/PSYCH-PHYS/behavioural;
load allkeys_39;
foo=all_sub_keys(2:end,1);
% roi_svm('/mnt/englewood/data','PSYCH-PHYS','SAX_DIS',...
%     'DIS_results_itemwise_normed',foo,24,[1 2],[6 7],...
%     {'acc' 'int'},'RTPJ','RTPJ_intVaccH_svm.mat')
% 
% roi_svm_leavetwo('/mnt/englewood/data','PSYCH-PHYS','SAX_DIS',...
%     'DIS_results_itemwise_normed',foo,24,[1 2],[6 7],...
%     {'acc' 'int'},'RTPJ','RTPJ_intVaccH_svmL2.mat')

roi_svm_leavetwo('/mnt/englewood/data','PSYCH-PHYS','SAX_DIS',...
    'DIS_results_itemwise_normed',foo,24,[1 2],[6 7],...
    {'acc' 'int'},'RTPJ','RTPJ_intVaccH_svmL2soft.mat')