
cd /mnt/englewood/data/PSYCH-PHYS/behavioural;
load allkeys_39;
foo=all_sub_keys(2:end,1);
% roi_svm('/mnt/englewood/data','PSYCH-PHYS','SAX_DIS',...
%     'DIS_results_itemwise_normed',foo,24,[1 2],[6 7],...
%     {'acc' 'int'},'RTPJ','RTPJ_intVaccH_svm.mat')
% 
% roi_svm_leavetwo('/mnt/englewood/data','PSYCH-PHYS','SAX_DIS',...
%     'DIS_results_itemwise_normed',foo,24,[1 2],[6 7],...
%     {'acc' 'int'},'RTPJ','RTPJ_intVaccH_svmL2.mat')

<<<<<<< HEAD
roi_svm_leavetwo('/mnt/englewood/data','PSYCH-PHYS','SAX_DIS',...
    'DIS_results_itemwise_normed',foo,24,[1 2],[6 7],...
    {'acc' 'int'},'RTPJ','RTPJ_intVaccH_svmL2soft.mat')
=======
% roi_svm_leavetwo('/mnt/englewood/data','PSYCH-PHYS','SAX_DIS',...
%     'DIS_results_itemwise_normed',foo,24,[3 4],[8 9],...
%     {'acc' 'int'},'LIFG','LIFG_intVaccH_svmL2soft.mat')

roi_svm_leavetwo('/mnt/englewood/data','PSYCH-PHYS','SAX_DIS',...
    'DIS_results_itemwise_normed',foo,48,[1 2 6 7],[3 4 8 9],...
    {'harm' 'purity'},'LIFG','LIFG_HvP_svmL2soft.mat')
>>>>>>> 4ea36e0abf8da612bbc2f8f0c2b7dc72c0a45376
