#!/bin/tcsh
#PBS -l mem=35gb,nodes=1:ppn=1,walltime=1:00:00
#PBS -m abe -M kevin.jiang@bc.edu
#PBS -N zkevin_predcm2bidsformatter_job
#PBS -t 1-3
#PBS -e /data/younglw/lab/scripts/fmriprep/aa_pbs_scripts/ztmp/$PBS_JOBNAME.e$PBS_JOBID
#PBS -o /data/younglw/lab/scripts/fmriprep/aa_pbs_scripts/ztmp/$PBS_JOBNAME.o$PBS_JOBID

python /data/younglw/lab/scripts/fmriprep/pre_dcm2bids_formatter.py --source TPS --dest deletemelater --studyname TPS --subnum ${PBS_ARRAYID}
