#!/bin/tcsh
#PBS -l mem=35gb,nodes=1:ppn=1,walltime=1:30:00
#PBS -m abe -M kevin.jiang@bc.edu
#PBS -N zkevin_dcm2bids_job528
#PBS -t 1-3
#PBS -e /data/younglw/lab/scripts/fmriprep/aa_pbs_scripts/ztmp/$PBS_JOBNAME.e$PBS_JOBID
#PBS -o /data/younglw/lab/scripts/fmriprep/aa_pbs_scripts/ztmp/$PBS_JOBNAME.o$PBS_JOBID

module load anaconda/4.4.0-P3.6

set sub_num = `printf "%02d" ${PBS_ARRAYID}`

python /data/younglw/lab/scripts/fmriprep/final_dcm2bids.py --indir /data/younglw/lab/deletemelater/dicoms --outdir /data/younglw/lab/deletemelater/hopefully_bids/ --infile /data/younglw/lab/deletemelater/full_infile_TPS.csv --single-sub YOU_TPS_${sub_num} --no-sessions

# python /data/younglw/lab/scripts/fmriprep/final_dcm2bids.py --indir /data/younglw/lab/TPS_FMRIPREP/dicoms --outdir /data/younglw/lab/TPS_FMRIPREP/hopefully_bids/ --infile /data/younglw/lab/TPS_FMRIPREP/full_infile_TPS.csv --no-sessions --keep-all-anats