% DIS_reanalyses
load(fullfile('/home/younglw/lab/server/englewood/mnt/englewood/data','PSYCH-PHYS','RSA_parameters.mat'));

% Within-ROI RSA: all feature variables
% note orthogonalization flag = 1
% rsa_roi('/home/younglw/lab/server/englewood/mnt/englewood/data',...
%       'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub_nums,[1:48],3,...
%       {'acc_wrong' 'act' 'disgweight' 'env' 'hother_scale' 'hself_scale' 'int_wrong' 'mind' 'person_attr' 'rationality' 'sit_attr' 'weird'},...
%       'purity_LIFG_2', 1, '_allfeat_LIFG_ortho');
% rsa_roi('/home/younglw/lab/server/englewood/mnt/englewood/data',...
%       'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub_nums,[1:48],3,...
%       {'acc_wrong' 'act' 'disgweight' 'env' 'hother_scale' 'hself_scale' 'int_wrong' 'mind' 'person_attr' 'rationality' 'sit_attr' 'weird'},...
%       'harm_PC_2',1, '_allfeat_PC_ortho');

% Load corrs for above
% load_corrs('/home/younglw/lab/server/englewood/mnt/englewood/data/',...
	% 'PSYCH-PHYS','DIS_results_itemwise_normed','harm_PC_2_allfeat_PC_ortho',sub_nums);
% load_corrs('/home/younglw/lab/server/englewood/mnt/englewood/data/',...
	% 'PSYCH-PHYS','DIS_results_itemwise_normed','purity_LIFG_2_allfeat_LIFG_ortho',sub_nums);

cat_reg_orig = {'phys' 'psyc' 'physVpsyc' 'inc' 'path' 'incVpath'};
for feat = {'acc_wrong' 'act' 'disgweight' 'env' 'hother_scale' 'hself_scale' 'int_wrong' 'mind' 'person_attr' 'rationality' 'sit_attr' 'weird'}
	cat_reg=cat_reg_orig;
	cat_reg{end+1}=feat{1};
	% rsa_roi('/home/younglw/lab/server/englewood/mnt/englewood/data',...
 %      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub_nums,[1:48],3,...
 %      cat_reg, 'purity_LIFG_2',2,['_' feat{1} '_ortho']);
	% rsa_roi('/home/younglw/lab/server/englewood/mnt/englewood/data',...
 %      'PSYCH-PHYS','SAX_DIS','DIS_results_itemwise_normed',sub_nums,[1:48],3,...
 %      cat_reg, 'harm_PC_2',2,['_' feat{1} '_ortho']);
	% load_corrs('/home/younglw/lab/server/englewood/mnt/englewood/data/',...
	% 	'PSYCH-PHYS','DIS_results_itemwise_normed',['purity_LIFG_2_' feat{1} '_ortho'],sub_nums);
	% load_corrs('/home/younglw/lab/server/englewood/mnt/englewood/data/',...
	% 	'PSYCH-PHYS','DIS_results_itemwise_normed',['harm_PC_2_' feat{1} '_ortho'],sub_nums);
	% permute_test_roi('/home/younglw/lab/server/englewood/mnt/englewood/data/','PSYCH-PHYS','DIS_results_itemwise_normed',sub_nums,['behav_matrix_' feat{1} '_ortho'],100,'purity_LIFG_2','purity_LIFG_2_cat_LIFG');
	permute_test_roi('/home/younglw/lab/server/englewood/mnt/englewood/data/','PSYCH-PHYS','DIS_results_itemwise_normed',sub_nums,['behav_matrix_' feat{1} '_ortho'],100,'harm_PC_2','harm_PC_2_cat_PC');
end

