% example script.
% This script will perform GcSS fROI analyses, using the contrast 'S-N'
% both as localizer contrast and contrast of interest (the toolbox will
% automatically break down these contrasts by sessions and perform
% cross-validation with the resulting session-specific estimates)
%

experiments(1)=struct(...
    'name','SWN',...% SWN expt 
    'pwd1','/groups/domspec/data/',...
    'pwd2','firstlevel_SWN',...
    'data',{{'domspec_01','domspec_03','domspec_04','domspec_05','domspec_06','domspec_07','domspec_08','domspec_09','domspec_10',...
	     'domspec_11','domspec_12','domspec_13'}});
experiments(2)=struct(...
    'name','domspec_subjects',...% music expt
    'pwd1','/groups/domspec/data/',...
    'pwd2','firstlevel_math',...
    'data',{{'domspec_01','domspec_03','domspec_04','domspec_05','domspec_06','domspec_07','domspec_08','domspec_09','domspec_10',...
	     'domspec_11','domspec_12','domspec_13'}});

epx1_spmfiles={};
for nsub=1:length(experiments(1).data),
    exp1_spmfiles{nsub}=fullfile(experiments(1).pwd1,experiments(1).data{nsub},experiments(1).pwd2,'SPM.mat');
end

exp2_spmfiles={};
for nsub=1:length(experiments(2).data),
    exp2_spmfiles{nsub}=fullfile(experiments(2).pwd1,experiments(2).data{nsub},experiments(2).pwd2,'SPM.mat');
end

ss=struct(...
    'swd','/groups/swjn/analysis/test_S-N_SWJN',...         % output directory
	'EffectOfInterest_spm',{cat(1,repmat(exp1_spmfiles,[3,1]),repmat(exp2_spmfiles,[2,1]))},...
	'Localizer_spm',{cat(1,exp1_spmfiles,exp2_spmfiles)},...
    'EffectOfInterest_contrasts',{{'S','W','N','H','E'}},...    % contrasts of interest
    'Localizer_contrasts',{{'S-N','H-E'}},...                     % localizer contrast (note: if these contrasts are not orthogonal the toolbox will automatically partition theses contrasts by sessions and perform cross-validation) 
    'Localizer_thr_type',{{'FDR','none'}},...
    'Localizer_thr_p',[.05,.05],...
    'type','mROI',...                                       % can be 'GcSS' (for automatically defined ROIs), 'mROI' (for manually defined ROIs), or 'voxel' (for voxel-based analyses)
    'smooth',6,...                                          % (FWHM mm)
    'ManualROIs','/groups/swjn/analysis/toolbox_SWJN_basic/test_REST-S-N_FDR05_FIRST-S-N/fROIs.img',...    
    'overlap_thr',.1,...
    'model',1,...                                           % can be 1 (one-sample t-test), 2 (two-sample t-test), or 3 (multiple regression)
    'estimation','ReML',...
    'ExplicitMasking',[],...
    'ask','missing');                                       % can be 'none' (any missing information is assumed to take default values), 'missing' (any missing information will be asked to the user), 'all' (it will ask for confirmation on each parameter)
ss=spm_ss_design(ss);                                          % see help spm_ss_design for additional information
ss=spm_ss_estimate(ss);





